name: "Isobel Parkin Lab "
description: "Park in the official web page for the Idobel Parkin Lab at AAFC, saskatoon."

url: "http://parkingenomics.githhub.io"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
